### PR TITLE
Feat/cache mybinder

### PR DESCRIPTION
**Pull request by mikemhenry**
Copied from here: https://github.com/jupyterhub/repo2docker-action#cache-builds-on-mybinderorg

There is a better option to use github actions to build the image, but requires a container registry. This is a "better" option since it offloads the image building to github instead of using mybinder's infrastructure. If someone wants to setup a dockerhub account, then create the following secrets, then I can modify this PR.
DOCKER_USERNAME
DOCKER_PASSWORD (don't use the password, create a token)

### CODE REVIEW

**Comment by mikemhenry** [comment]
Something is wierd
https://github.com/glotzerlab/freud-examples/actions/runs/840345415
The actions are running but don't show up in the box, they did until pre-commit.ci showed an error, but it did pass? I'm going to bump with an empty commit to see if that can fix things

**Comment by bdice** [comment]
Let’s ignore that file in pre-commit’s config for the end-of-file fixer.

**Comment by mikemhenry** [comment]
image
Okay so they show up, lets see if this dissaper again

**Comment by mikemhenry** [comment]
I think there is a really weird interaction going on with the pre-commit + the bot creating that file?
https://results.pre-commit.ci/repo/github/143797814

**Comment by bdice** [comment]
I'm going to close this PR and make a new PR with the same contents, to see if that helps fix CI.

**Pull request closed without merging**
