### PR TITLE
Cache Docker image for mybinder.

### PR DESCRIPTION
**Pull request by bdice**
Duplicate of #27, attempting to make CI work.

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
@mikemhenry I think the problem may be solved here. GitHub Actions won't run on commits pushed by the GitHub Actions bot. I think Josh solved this for another repository by creating a separate bot, so that GHA still runs. If you agree that this looks good, please approve this PR and we can merge it.

**Comment by joaander** [comment]
Yes, pushes or pull requests created by GitHub Actions do not trigger actions to run in order to help prevent infinite loops.

If you need actions to create PRs, I do have a bot account we can use for that on the glotzerlab org - here is one example using it: https://github.com/glotzerlab/software/blob/master/.github/workflows/update-packages.yml

Otherwise, the simplest and most secure workaround is to close and reopen the PR. The other various options and their pros and cons are documented here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

**Review by mikemhenry — APPROVED** [review]
LGTM, should work, I think the pre-commit bot is the bot breaking this

**Comment by bdice** [comment]
@mikemhenry Just to clarify -- the pre-commit bot isn't breaking anything and we're seeing the expected behavior.

On our commit b0a6735, all four checks (three from GitHub Actions and one from pre-commit bot) all executed successfully. On commit a7f6d3b, which was made by the GitHub Actions bot, only the pre-commit check ran. That's because GitHub Actions do not trigger on commits _pushed by GitHub Actions_.

**Pull request merged**
