### PR TITLE
RDF Example Updates

### PR DESCRIPTION
**Pull request by tommy-waltmann**
## Description

This PR updates the RDF example to the new v3 api and clarifies some wording which was not updated from freud v1 -> v2

Resolves: #54 , ~~partially~~ fully #59 

## Checklist:

- [ ] I agree with the terms of the [**freud Contributor Agreement**](https://github.com/glotzerlab/freud-examples/blob/master/ContributorAgreement.md).
- [ ] My code follows the code style of this project.
- [ ] I have updated the [index notebook](https://github.com/glotzerlab/freud-examples/blob/master/index.ipynb) if needed.
- [ ] My name is on the [contributors list](https://github.com/glotzerlab/freud-examples/blob/master/contributors.txt).

### CODE REVIEW

**Comment by tommy-waltmann** [comment]
I have manually checked and this PR is failing the tests it should fail, and passing the tests it should pass.

**Comment by SchoeniPhlippsn** [comment]
I will review this once I am back from APS

**Comment by tommy-waltmann** [comment]
Upon further inspection, this PR will fully resolve #59 . I'll update the PR description now.

**Review by SchoeniPhlippsn — APPROVED** [review]
Sorry, it took so long for such a straightforward review. I don't have any issues.

**Pull request merged**
