### PR TITLE
add RDF example with excluding bonded neighbors and selecting particle types

### PR DESCRIPTION
**Pull request by jennyfothergill**
Here's a start--it runs pretty slow and I'm sure it could be more efficient. Thanks for your help!

### CODE REVIEW

**Comment by vyasr** [comment]
@jennyfothergill thanks, this is great! I didn't really review this yet, but one thing I'd definitely suggest is using scipy for [connected components](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.connected_components.html). That should simplify your example.

**Comment by jennyfothergill** [comment]
@vyasr this is a great suggestion and it looks like it's much faster! (especially if I build the graph a little differently than the example) I'm having a little trouble implementing it though. It keeps returning the wrong number of molecules. Note: when I did it the same way as the example (e.g. an NxN numpy array with ones representing bonds) it also returned 5000 components...

```
row = []
col = []
for i,j in snap.bonds.group:
    row.append(i)
    col.append(j)
    
N = snap.bonds.N
data = np.ones(N)
row = np.array(row)
col = np.array(col)

bond_graph = csr_matrix((data,(row,col)), shape=(N,N))
n_components, labels = connected_components(csgraph=bond_graph, directed=False)
```
n_components --> 5000 when it should be 200

len(get_molecules(snap)) --> 200

Do you know what I am doing wrong? I've pushed my most recent changes with some timing showing we do get a speedup using scipy's connected components. :)

**Comment by vyasr** [comment]
@jennyfothergill The issue looks to be that you're `bond_graph` is the wrong shape. You need the N in the shape to be the number of particles, not the number of bonds, because each element in the matrix indicates that particle i is bonded to particle j. Also, you don't need to construct the row and col arrays, you can directly index into the bonds using numpy slices. Something like:

```
bond_graph = csr_matrix((np.ones(snap.bonds.N), (snap.bonds.group[:, 0], snap.bonds.group[:, 1])), shape=(snap.particles.N, snap.particles.N))
n_components, labels = connected_components(csgraph=bond_graph, directed=False)
```

Try that and see if it fixes your problem? I'm just having a look on my phone, but I can pull it up later on my computer if you need more help!

**Comment by mikemhenry** [comment]
I'm really excited for this example, @jennyfothergill  let me know if you want any help!

**Comment by jennyfothergill** [comment]
@vyasr thank you! Your suggestion to remove the for loop was 2x faster resulting in a 4x speedup over what I was originally doing. (idk why I was using a for loop there anyway haha) :) I ran into some weirdness learning that generators cease to exist after they're iterated over, but I think everything should be working now.
Here's what I'm thinking for next steps:
- add markdown explanations/pictures to help support why this might be important. I'm thinking a picture that shows the length between the sulfurs in the same molecule and relates that to the RDF.
- the y-axis values on the rdf seem very low, look into using some normalization?
This code is still takes a minute but I think the slow step is the neighborlist creation and filtering... Originally I was creating the neighborlist from only the A and B type positions and that might be faster, but then the problem of filtering the intramolecular interactions is harder because the indices change.

**Comment by vyasr** [comment]
<p>Yup, generators will vanish after one iteration! Glad you figured that out. This will definitely be a great example! I agree that adding markdown notes etc would be a great next step so that the example is well documented.</p><p> </p><p>Here are some more suggestions for improvement that should also make this faster (all line numbers are based on the line numbers on ReviewNB, which you can open up from the link in one of the first comments on this PR by a bot):</p><ul><li>You don't need to use pygsd at all. replace the first three lines of <code>gsd_rdf</code>  with <code>with gsd.hoomd.open(file) as traj</code>.  That will not only be simpler, but also faster because you will read the file using the C API of gsd.</li><li>Trajectories support direct indexing and slicing, so you can replace all your <code>start</code>/<code>stop</code>   logic (lines 100-106) with <code>for frame in traj[start:stop]</code>. </li><li>Your neighborlist type filtering could also be simplified and probably sped up using vectorized code. Everything starting with <code>type_A</code>   up to the first call to filter (lines 111-119) could be done more simply: <code>nlist.filter(snap.particles.typeid[nlist.query_point_indices] != snap.particles.typeid[nlist.point_indices])</code>  Admittedly this assumes that you have a binary system, unlike your code which accepts type names, but I think that's an acceptable simplification here.</li><li>You can also do the same thing with your second filter: <code>nlist.filter(molecules[nlist.query_point_indices] != molecules[nlist.point_indices])</code> .</li><li>You're right, the y axis looks off. The issue is almost certainly what is discussed on #396 and #529. The short version is that it's probably dividing by all possible pairs of particles rather than accounting for the actual number of pairs that you're including in your RDF (since you're limiting the neighbors that "count" towards the RDF). This issue originally popped up in #396, and I opted to employ a very simple rescaling solution in #529 that would avoid finite size issues for single-component systems because I figured that the multi-component use case was probably not a frequent one. Now that it's popped up, if you'd like to take a stab at fixing it let me know and I can help you with it! I know how to address the problem and it would be a nice chance for you to take a stab at a little C++ coding if you haven't tried before. Feel free to ping if you're interested, I don't think this will be a terribly difficult problem to address (the proposed solution is documented on #529 I believe).</li></ul>

**Comment by jennyfothergill** [comment]
@vyasr Thank you so much for all your help! 

> Trajectories support direct indexing and slicing, so you can replace all your start/stop logic (lines 100-106) with for frame in traj[start:stop]. 

I've been reusing this code for a while and I think this was from back when gsd did weird things given out-of-bounds indices... but PRs #27 and #31 have long since been merged!

Your vectorizing suggestions are so clean, thank you! 🤩 I'm not that good at thinking this way yet, so I really appreciate your help.

I'm happy to give it a try! It looks like Josh linked a paper on using pair counting for the normalization, is that right?

**Comment by vyasr** [comment]
No problem, happy to help. Yes, GSD had some early issues with slicing but now everything is good!

Yes, if you're interested we can try and resolve this! I'll reopen the relevant issue and we can continue the discussion there.

**Comment by jennyfothergill** [comment]
I'm noticing that in my example `query_point_indices` is never different from `point_indices` (see latest commit 3f2153f), which is a little confusing to me because I thought that was what was messing up the normalization. Should I be looking at a set of the indices (each index only counted once) and not the pairs?

**Comment by bdice** [comment]
@jennyfothergill I pushed some changes to the notebook. It looks good overall, and I also saw the slow behavior of `filter` that you commented on earlier. I have opened a PR to help speed that up: https://github.com/glotzerlab/freud/pull/714

I'm going to make one more review pass and then I think this can be merged. Further improvements (such as adding this normalization natively in freud's RDF) can be done in follow-up PRs. Thanks again for your effort on this!

**Comment by bdice** [comment]
A few of the specific improvements that I made:
- Renaming variables, improving docstrings, grammar, etc.
- Use `exclude_ii` in the query API instead of requiring a non-zero `r_min`
- Improved default calculation of `r_max` to use `max(L)/2` (rounded down by an infinitesimal amount)
- Formatted code with `black` (JupyterLab plugin)

**Review by bdice — APPROVED** [review]
Looks good. Merging.

**Comment by jennyfothergill** [comment]
@vyasr and @bdice Thank you both so much for your help!

**Pull request merged**
